#!/usr/bin/env node
/** Regenerate content.js from lessons/*.md and cheatsheet.md (for file:// without fetch). */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const lessonsDir = path.join(root, "lessons");
const lessons = {};

for (const f of fs.readdirSync(lessonsDir).filter(x => x.endsWith(".md")).sort()) {
  lessons[`lessons/${f}`] = fs.readFileSync(path.join(lessonsDir, f), "utf8");
}

const cheatsheet = fs.readFileSync(path.join(root, "cheatsheet.md"), "utf8");
const simpleWordsPath = path.join(root, "SIMPLE_WORDS.md");
const simpleWords = fs.existsSync(simpleWordsPath)
  ? fs.readFileSync(simpleWordsPath, "utf8")
  : "# SIMPLE_WORDS.md not found\n";

const standartPath = path.join(root, "STANDART.md");
const standart = fs.existsSync(standartPath)
  ? fs.readFileSync(standartPath, "utf8")
  : "# STANDART.md not found\n";

const out = [
  "// Generated by scripts/build-content.js — do not edit by hand",
  "const LESSON_MD = " + JSON.stringify(lessons) + ";",
  "const CHEATSHEET_MD = " + JSON.stringify(cheatsheet) + ";",
  "const SIMPLE_WORDS_MD = " + JSON.stringify(simpleWords) + ";",
  "const STANDART_MD = " + JSON.stringify(standart) + ";",
  ""
].join("\n");

fs.writeFileSync(path.join(root, "content.js"), out);
console.log(`OK: ${Object.keys(lessons).length} lessons → content.js`);