#!/usr/bin/env node
/** Regenerate content.js from lessons/*.md and cheatsheet.md (for file:// without fetch). */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const lessonsDir = path.join(root, "lessons");
const lessons = {};

for (const f of fs.readdirSync(lessonsDir).filter(x => x.endsWith(".md")).sort()) {
  lessons[`lessons/${f}`] = fs.readFileSync(path.join(lessonsDir, f), "utf8");
}

const cheatsheet = fs.readFileSync(path.join(root, "cheatsheet.md"), "utf8");
const out = [
  "// Generated by scripts/build-content.js — do not edit by hand",
  "const LESSON_MD = " + JSON.stringify(lessons) + ";",
  "const CHEATSHEET_MD = " + JSON.stringify(cheatsheet) + ";",
  ""
].join("\n");

fs.writeFileSync(path.join(root, "content.js"), out);
console.log(`OK: ${Object.keys(lessons).length} lessons → content.js`);